/**
 * content.js — Auto-generated from config.js
 *
 * ⚠️  不要直接修改这个文件
 * ⚠️  Do NOT edit this file directly
 *
 * 所有内容请修改 config.js
 * All content should be edited in config.js
 */

/* ================================================================
   Build CONTENT from CONFIG
   ================================================================ */
(function () {

  /* ── helpers ── */
  function t(field, lang) {
    if (!field) return '';
    if (typeof field === 'string') return field;
    return field[lang] || field['en'] || '';
  }

  function buildStrings(lang) {
    var C = CONFIG;
    var nameDisplay = lang === 'zh'
      ? (C.name.alias + '<br><span style="color:var(--pink)">' + C.name.zh + '</span>')
      : (C.name.alias + '<br><span style="color:var(--pink)">' + C.name.en + '</span>');

    return {
      /* ── Nav ── */
      'nav.home':      lang === 'zh' ? '首页'  : 'Home',
      'nav.portfolio': lang === 'zh' ? '作品集' : 'Portfolio',
      'nav.resume':    lang === 'zh' ? '简历'  : 'Resume',
      'nav.about':     lang === 'zh' ? '关于我' : 'About',
      'nav.toggle':    lang === 'zh' ? 'EN'    : '中文',

      /* ── Footer ── */
      'footer.portfolio': lang === 'zh' ? '作品集' : 'Portfolio',
      'footer.resume':    lang === 'zh' ? '简历'   : 'Resume',
      'footer.contact':   lang === 'zh' ? '联系'   : 'Contact',
      'footer.copy':      C.copyright,

      /* ── Home ── */
      'index.eyebrow':       t(C.role, lang),
      'index.subtitle':      t(C.home.subtitle, lang),
      'index.btn.portfolio': lang === 'zh' ? '查看作品集' : 'View Portfolio',
      'index.btn.contact':   lang === 'zh' ? '联系我'    : 'Contact Me',
      'index.scroll':        'Scroll',

      'index.about.label':   'About',
      'index.about.title':   t(C.home.about.title, lang),
      'index.about.desc':    t(C.home.about.desc,  lang),
      'index.about.resume':  lang === 'zh' ? '查看简历' : 'View Resume',

      'index.stat1.num':   C.home.stats[0] ? C.home.stats[0].num : '',
      'index.stat1.label': C.home.stats[0] ? t(C.home.stats[0].label, lang) : '',
      'index.stat2.num':   C.home.stats[1] ? C.home.stats[1].num : '',
      'index.stat2.label': C.home.stats[1] ? t(C.home.stats[1].label, lang) : '',
      'index.stat3.num':   C.home.stats[2] ? C.home.stats[2].num : '',
      'index.stat3.label': C.home.stats[2] ? t(C.home.stats[2].label, lang) : '',
      'index.stat4.num':   C.home.stats[3] ? C.home.stats[3].num : '',
      'index.stat4.label': C.home.stats[3] ? t(C.home.stats[3].label, lang) : '',

      'index.featured.label':   'Featured Works',
      'index.featured.title':   lang === 'zh' ? '精选作品' : 'Featured Works',
      'index.featured.viewall': lang === 'zh' ? '查看全部 →' : 'View All →',

      'index.feat1.tag':   CONFIG.works[0] ? (CONFIG.works[0].tags[0] || '') : '',
      'index.feat1.title': CONFIG.works[0] ? t(CONFIG.works[0].title, lang)  : '',
      'index.feat2.tag':   CONFIG.works[1] ? (CONFIG.works[1].tags[0] || '') : '',
      'index.feat2.title': CONFIG.works[1] ? t(CONFIG.works[1].title, lang)  : '',
      'index.feat3.tag':   CONFIG.works[2] ? (CONFIG.works[2].tags[0] || '') : '',
      'index.feat3.title': CONFIG.works[2] ? t(CONFIG.works[2].title, lang)  : '',

      'index.skills.label': 'Skills',
      'index.skills.title': lang === 'zh' ? '技术栈' : 'Tech Stack',

      /* ── Portfolio ── */
      'portfolio.label': 'Portfolio',
      'portfolio.title': lang === 'zh' ? '作品集' : 'Portfolio',
      'portfolio.desc':  lang === 'zh'
        ? 'Shader、特效、工具开发与渲染实验——技术与美学的交叉探索。'
        : 'Shaders, VFX, tools, and rendering experiments — exploring the intersection of technique and aesthetics.',
      'portfolio.section.project': lang === 'zh' ? '完整项目作品' : 'Complete Projects',
      'portfolio.section.art':     lang === 'zh' ? '独立美术作品' : 'Independent Artworks',
      'portfolio.empty.project':   lang === 'zh' ? '暂无完整项目作品' : 'No complete projects yet.',
      'portfolio.empty.art':       lang === 'zh' ? '暂无独立美术作品' : 'No independent artworks yet.',

      'filter.all':    lang === 'zh' ? '全部'    : 'All',
      'filter.shader': lang === 'zh' ? 'Shader'  : 'Shader',
      'filter.vfx':    lang === 'zh' ? '特效 VFX': 'VFX',
      'filter.tool':   lang === 'zh' ? '工具 Tools':'Tools',
      'filter.render': lang === 'zh' ? '渲染 Render':'Render',
      'filter.code':   lang === 'zh' ? '代码 Code': 'Code',
      'no.results':    lang === 'zh' ? '没有找到该分类的作品' : 'No works found in this category.',

      /* ── Resume ── */
      'resume.eyebrow': t(C.role, lang),
      'resume.name':    lang === 'zh'
        ? C.name.zh
        : (C.name.en.split(' ')[0] + ' <span class="text-pink">' + C.name.en.split(' ').slice(1).join(' ') + '</span>'),
      'resume.tel':     'TEL: ' + C.contact.tel,
      'resume.email':   'EMAIL: ' + C.contact.email,
      'resume.contact': lang === 'zh' ? '联系我' : 'Contact Me',

      'resume.education.title': lang === 'zh' ? '教育经历'     : 'Education',
      'resume.work.title':      lang === 'zh' ? '工作经历'     : 'Work Experiences',
      'resume.indie.title':     lang === 'zh' ? '独立项目经历'  : 'Indie Project Experiences',
      'resume.skills.title':    lang === 'zh' ? '技能 & 证书'  : 'Certificates & Skills',

      /* ── About ── */
      'about.label': 'About Me',
      'about.name':  nameDisplay,
      'about.role':  t(C.role, lang).replace('·', '·').replace(/ · /, ' · <span style="color:var(--pink)">').replace(/([^>]+)$/, '$1</span>'),
      'about.bio':   t(C.about.bio, lang),

      'about.info.title':      lang === 'zh' ? '个人信息'  : 'Personal Info',
      'about.info.name.key':   lang === 'zh' ? '姓名'      : 'Name',
      'about.info.name.val':   C.name.en + (C.name.zh ? ' · ' + C.name.zh : ''),
      'about.info.job.key':    lang === 'zh' ? '职业'      : 'Role',
      'about.info.job.val':    t(C.role, lang),
      'about.info.loc.key':    lang === 'zh' ? '所在地'    : 'Location',
      'about.info.loc.val':    t(C.location, lang),
      'about.info.exp.key':    lang === 'zh' ? '经验'      : 'Experience',
      'about.info.exp.val':    t(C.experience, lang),
      'about.info.lang.key':   lang === 'zh' ? '语言'      : 'Languages',
      'about.info.lang.val':   t(C.languages, lang),
      'about.info.status.key': lang === 'zh' ? '状态'      : 'Status',
      'about.info.status.val': t(C.status, lang),
      'about.info.desc':       t(C.about.desc, lang),

      'about.contact.title':   lang === 'zh' ? '联系我'    : 'Contact',
      'contact.email.label':    lang === 'zh' ? '邮件'      : 'Email',
      'contact.github.label':   lang === 'zh' ? 'GitHub'    : 'GitHub',
      'contact.artstation.label': lang === 'zh' ? 'ArtStation' : 'ArtStation',
      'contact.linkedin.label': lang === 'zh' ? 'LinkedIn'  : 'LinkedIn',
      'about.interests.title': lang === 'zh' ? '兴趣与方向' : 'Interests & Directions',
    };
  }

  /* ── Build works array for a given language ── */
  function buildWorks(lang) {
    return CONFIG.works.map(function (w) {
      var bgStyle = w.image
        ? "background-image: url('" + w.image + "'); background-size: cover; background-position: center;"
        : '';
      return {
        category: w.category,
        group:    w.group || ((w.category === 'tool' || w.category === 'code') ? 'project' : 'art'),
        bgStyle:  bgStyle,
        hasVideo: !!w.hasVideo,
        tags:     w.tags,
        title:    t(w.title, lang),
        desc:     t(w.desc,  lang),
        links:    w.links.map(function (l) {
          return { label: t(l.label, lang), href: l.href };
        }),
      };
    });
  }

  /* ── Build education array ── */
  function buildEducation(lang) {
    return CONFIG.education.map(function (e) {
      return {
        school: t(e.school, lang),
        period: t(e.period, lang),
        degree: t(e.degree, lang),
        detail: t(e.detail, lang),
        award:  t(e.award,  lang),
      };
    });
  }

  /* ── Build work experience array ── */
  function buildWorkExp(lang) {
    return CONFIG.workExp.map(function (e) {
      return {
        company:    t(e.company, lang),
        period:     t(e.period, lang),
        role:       t(e.role,   lang),
        projectUrl: e.projectUrl || '',
        bullets:    e.bullets.map(function (b) { return t(b, lang); }),
      };
    });
  }

  /* ── Build indie projects array ── */
  function buildIndieProjects(lang) {
    return CONFIG.indieProjects.map(function (e) {
      return {
        title:      e.title,
        period:     t(e.period, lang),
        role:       t(e.role,   lang),
        projectUrl: e.projectUrl || '',
        award:      t(e.award,  lang),
        bullets:    e.bullets.map(function (b) { return t(b, lang); }),
      };
    });
  }

  /* ── Build interests array ── */
  function buildInterests(lang) {
    return CONFIG.about.interests.map(function (i) {
      return {
        icon:  i.icon,
        title: t(i.title, lang),
        desc:  t(i.desc,  lang),
      };
    });
  }

  /* ── Assemble CONTENT ── */
  window.CONTENT = {
    zh: buildStrings('zh'),
    en: buildStrings('en'),

    works:          { zh: buildWorks('zh'),          en: buildWorks('en')          },
    education:      { zh: buildEducation('zh'),      en: buildEducation('en')      },
    workExp:        { zh: buildWorkExp('zh'),         en: buildWorkExp('en')        },
    indieProjects:  { zh: buildIndieProjects('zh'),  en: buildIndieProjects('en')  },
    interests:      { zh: buildInterests('zh'),      en: buildInterests('en')      },
  };

}());
