/**
 * content.js — Auto-generated from config.js
 *
 * ⚠️  不要直接修改这个文件
 * ⚠️  Do NOT edit this file directly
 *
 * 所有内容请修改 config.js
 * All content should be edited in config.js
 */

/* ================================================================
   Build CONTENT from CONFIG
   ================================================================ */
(function () {

  /* ── helpers ── */
  function t(field, lang) {
    if (!field) return '';
    if (typeof field === 'string') return field;
    return field[lang] || field['en'] || '';
  }

  function buildStrings(lang) {
    var C = CONFIG;
    var nameDisplay = t(C.name, lang);

    return {
      /* ── Nav ── */
      'nav.home':      lang === 'zh' ? '首页'  : 'Home',
      'nav.portfolio': lang === 'zh' ? '作品集' : 'Portfolio',
      'nav.resume':    lang === 'zh' ? '简历'  : 'Resume',
      'nav.contact':   lang === 'zh' ? '联系'  : 'Contact',
      'nav.toggle':    lang === 'zh' ? 'EN'    : '中文',

      /* ── Footer ── */
      'footer.portfolio': lang === 'zh' ? '作品集' : 'Portfolio',
      'footer.resume':    lang === 'zh' ? '简历'   : 'Resume',
      'footer.contact':   lang === 'zh' ? '联系'   : 'Contact',
      'footer.copy':      C.copyright,

      /* ── Home ── */
      'index.eyebrow':       t(C.role, lang),
      'index.subtitle':      t(C.home.subtitle, lang),
      'index.btn.portfolio': lang === 'zh' ? '查看作品集' : 'View Portfolio',
      'index.btn.contact':   lang === 'zh' ? '联系我'    : 'Contact Me',
      'index.scroll':        'Scroll',

      'index.about.label':   'About',
      'index.about.title':   t(C.home.about.title, lang),
      'index.about.desc':    t(C.home.about.desc,  lang),
      'index.about.resume':  lang === 'zh' ? '查看简历' : 'View Resume',

      'index.stat1.num':   C.home.stats[0] ? C.home.stats[0].num : '',
      'index.stat1.label': C.home.stats[0] ? t(C.home.stats[0].label, lang) : '',
      'index.stat2.num':   C.home.stats[1] ? C.home.stats[1].num : '',
      'index.stat2.label': C.home.stats[1] ? t(C.home.stats[1].label, lang) : '',
      'index.stat3.num':   C.home.stats[2] ? C.home.stats[2].num : '',
      'index.stat3.label': C.home.stats[2] ? t(C.home.stats[2].label, lang) : '',
      'index.stat4.num':   C.home.stats[3] ? C.home.stats[3].num : '',
      'index.stat4.label': C.home.stats[3] ? t(C.home.stats[3].label, lang) : '',

      'index.featured.label':   'Featured Works',
      'index.featured.title':   lang === 'zh' ? '精选作品' : 'Featured Works',
      'index.featured.viewall': lang === 'zh' ? '查看全部 →' : 'View All →',

      'index.feat1.tag':   CONFIG.works[0] ? (CONFIG.works[0].tags[0] || '') : '',
      'index.feat1.title': CONFIG.works[0] ? t(CONFIG.works[0].title, lang)  : '',
      'index.feat2.tag':   CONFIG.works[1] ? (CONFIG.works[1].tags[0] || '') : '',
      'index.feat2.title': CONFIG.works[1] ? t(CONFIG.works[1].title, lang)  : '',
      'index.feat3.tag':   CONFIG.works[2] ? (CONFIG.works[2].tags[0] || '') : '',
      'index.feat3.title': CONFIG.works[2] ? t(CONFIG.works[2].title, lang)  : '',

      'index.skills.label': 'Skills',
      'index.skills.title': lang === 'zh' ? '技术栈' : 'Tech Stack',

      /* ── Portfolio ── */
      'portfolio.label': 'Portfolio',
      'portfolio.title': lang === 'zh' ? '作品集' : 'Portfolio',
      'portfolio.intro.role': t(C.role, lang),
      'portfolio.intro.name': lang === 'zh' ? C.name.zh : C.name.en,
      'portfolio.intro.copy': 'Shaders / Tools / Animation / PCG',
      'portfolio.works': lang === 'zh' ? '作品集' : 'Works',
      'portfolio.desc':  lang === 'zh'
        ? 'Shader、特效、工具开发与渲染实验——技术与美学的交叉探索。'
        : 'Shaders, VFX, tools, and rendering experiments — exploring the intersection of technique and aesthetics.',
      'portfolio.section.project': t((C.workGroupNames && C.workGroupNames.project) || { en: 'Complete Projects', zh: '完整项目作品' }, lang),
      'portfolio.section.tool':    t((C.workGroupNames && C.workGroupNames.tool) || { en: 'Tools', zh: '工具作品' }, lang),
      'portfolio.section.art':     t((C.workGroupNames && C.workGroupNames.art) || { en: 'Independent Works', zh: '独立作品' }, lang),
      'portfolio.empty.project':   lang === 'zh' ? '暂无完整项目作品' : 'No complete projects yet.',
      'portfolio.empty.tool':      lang === 'zh' ? '暂无工具作品' : 'No tools yet.',
      'portfolio.empty.art':       lang === 'zh' ? '暂无独立作品' : 'No independent works yet.',
      'filter.all': lang === 'zh' ? '全部' : 'All',
      'filter.shader': lang === 'zh' ? '着色器' : 'Shader',
      'filter.vfx':    lang === 'zh' ? '特效 VFX': 'VFX',
      'filter.tool': lang === 'zh' ? '工具' : 'Tools',
      'filter.pcg': lang === 'zh' ? '程序化生成' : 'PCG',
      'filter.render': lang === 'zh' ? '渲染' : 'Render',
      'filter.code': lang === 'zh' ? '代码' : 'Code',
      'no.results':    lang === 'zh' ? '没有找到该分类的作品' : 'No works found in this category.',

      /* ── Resume ── */
      'resume.eyebrow': t(C.role, lang),
      'resume.name': t(C.name, lang),
      'resume.tel':     'TEL: ' + C.contact.tel,
      'resume.email':   'EMAIL: ' + C.contact.email,
      'resume.contact': lang === 'zh' ? '联系我' : 'Contact Me',

      'resume.education.title': lang === 'zh' ? '教育经历'     : 'Education',
      'resume.work.title':      lang === 'zh' ? '工作经历'     : 'Work Experiences',
      'resume.indie.title':     lang === 'zh' ? '独立项目经历'  : 'Indie Project Experiences',
      'resume.skills.title':    lang === 'zh' ? '技能 & 证书'  : 'Certificates & Skills',
      'resume.skills.languages': lang === 'zh' ? '语言' : 'Languages',
      'resume.skills.label': lang === 'zh' ? '技能' : 'Skills',
      'resume.skills.ielts': lang === 'zh' ? '雅思 8.0' : 'IELTS 8.0',
      'resume.skills.cet6': lang === 'zh' ? '大学英语六级' : 'CET-6',
      'resume.skills.japanese': lang === 'zh' ? '日语三级' : 'Japanese CET-3',
      'resume.skills.unity': lang === 'zh' ? 'Unity C# 程序开发' : 'Unity C#',
      'resume.skills.shader': lang === 'zh' ? 'CG / HLSL 着色器开发' : 'CG / HLSL',
      'resume.skills.blueprint': lang === 'zh' ? 'UE 蓝图' : 'UE Blueprint',
      'resume.skills.python': lang === 'zh' ? 'Python 工具开发' : 'Python',
      'resume.skills.maya': lang === 'zh' ? 'Maya 3D 建模' : 'Maya',
      'resume.skills.substance': lang === 'zh' ? 'Substance 材质制作' : 'Substance',
      'resume.skills.houdini': lang === 'zh' ? 'Houdini 程序化制作' : 'Houdini',
      'resume.skills.video': lang === 'zh' ? 'Premiere / After Effects 影视后期' : 'Premiere / After Effects',
      'resume.skills.photoshop': lang === 'zh' ? 'Photoshop 图像处理' : 'Photoshop',
      'resume.skills.davinci': lang === 'zh' ? 'DaVinci Resolve 调色' : 'DaVinci Resolve',

      /* ── About ── */
      'about.label': 'About Me',
      'about.name':  nameDisplay,
      'about.role': t(C.role, lang),
      'about.bio':   t(C.about.bio, lang),

      'about.info.title':      lang === 'zh' ? '个人信息'  : 'Personal Info',
      'about.info.name.key':   lang === 'zh' ? '姓名'      : 'Name',
      'about.info.name.val':   C.name.en + (C.name.zh ? ' · ' + C.name.zh : ''),
      'about.info.job.key':    lang === 'zh' ? '职业'      : 'Role',
      'about.info.job.val':    t(C.role, lang),
      'about.info.loc.key':    lang === 'zh' ? '所在地'    : 'Location',
      'about.info.loc.val':    t(C.location, lang),
      'about.info.exp.key':    lang === 'zh' ? '经验'      : 'Experience',
      'about.info.exp.val':    t(C.experience, lang),
      'about.info.lang.key':   lang === 'zh' ? '语言'      : 'Languages',
      'about.info.lang.val':   t(C.languages, lang),
      'about.info.status.key': lang === 'zh' ? '状态'      : 'Status',
      'about.info.status.val': t(C.status, lang),
      'about.info.desc':       t(C.about.desc, lang),

      'about.contact.title':   lang === 'zh' ? '联系我'    : 'Contact',
      'contact.email.label':    lang === 'zh' ? '邮件'      : 'Email',
      'contact.github.label':   lang === 'zh' ? 'GitHub'    : 'GitHub',
      'contact.artstation.label': lang === 'zh' ? 'ArtStation' : 'ArtStation',
      'contact.linkedin.label': lang === 'zh' ? 'LinkedIn'  : 'LinkedIn',
      'contact.website.label':  lang === 'zh' ? '网站'      : 'Website',
      'contact.page.title':     lang === 'zh' ? '联系'      : 'Contact',
      'contact.page.role':      t(C.role, lang),
      'about.interests.title': lang === 'zh' ? '兴趣与方向' : 'Interests & Directions',
    };
  }

  /* ── Build works array for a given language ── */
  function buildWorks(lang) {
    return CONFIG.works.map(function (w, index) {
      var bgStyle = w.image
        ? "background-image: url('" + w.image + "'); background-size: cover; background-position: center;"
        : '';
      return {
        category: w.category,
        id:       index,
        group:    w.group || (w.category === 'tool' ? 'tool' : ((w.category === 'code' || w.category === 'pcg') ? 'project' : 'art')),
        bgStyle:  bgStyle,
        hasVideo: !!w.hasVideo,
        tags:     w.tags,
        title:    t(w.title, lang),
        desc:     t(w.desc,  lang),
        pdf:      w.pdf || '',
        links:    w.links.map(function (l) {
          return { type: l.type || '', label: t(l.label, lang), href: l.href };
        }),
      };
    });
  }

  /* ── Build education array ── */
  function buildEducation(lang) {
    return CONFIG.education.map(function (e) {
      return {
        school: t(e.school, lang),
        period: t(e.period, lang),
        degree: t(e.degree, lang),
        detail: t(e.detail, lang),
        award:  t(e.award,  lang),
      };
    });
  }

  /* ── Build work experience array ── */
  function buildWorkExp(lang) {
    return CONFIG.workExp.map(function (e) {
      return {
        company:    t(e.company, lang),
        period:     t(e.period, lang),
        role:       t(e.role,   lang),
        projectUrl: e.projectUrl || '',
        bullets:    e.bullets.map(function (b) { return t(b, lang); }),
      };
    });
  }

  /* ── Build indie projects array ── */
  function buildIndieProjects(lang) {
    return CONFIG.indieProjects.map(function (e) {
      return {
        title:      e.title,
        period:     t(e.period, lang),
        role:       t(e.role,   lang),
        projectUrl: e.projectUrl || '',
        award:      t(e.award,  lang),
        bullets:    e.bullets.map(function (b) { return t(b, lang); }),
      };
    });
  }

  /* ── Build interests array ── */
  function buildInterests(lang) {
    return CONFIG.about.interests.map(function (i) {
      return {
        icon:  i.icon,
        title: t(i.title, lang),
        desc:  t(i.desc,  lang),
      };
    });
  }

  /* ── Assemble CONTENT ── */
  window.CONTENT = {
    zh: buildStrings('zh'),
    en: buildStrings('en'),

    works:          { zh: buildWorks('zh'),          en: buildWorks('en')          },
    education:      { zh: buildEducation('zh'),      en: buildEducation('en')      },
    workExp:        { zh: buildWorkExp('zh'),         en: buildWorkExp('en')        },
    indieProjects:  { zh: buildIndieProjects('zh'),  en: buildIndieProjects('en')  },
    interests:      { zh: buildInterests('zh'),      en: buildInterests('en')      },
  };

}());
